# See https://docs.travis-ci.com/user/languages/r/
language: r
cache: packages
  
notifications:
  email: false

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'



# Will fail with WARNINGS from R CMD check.  Uncomment to ignore WARNINGS.
# warnings_are_errors: false
